spring.application.name=ecom-api-gateway

# Order service Static route
#spring.cloud.gateway.server.webflux.routes[0].id=order-service
#spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8080
#spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/orders/**

# Order service Dynamic route
spring.cloud.gateway.server.webflux.routes[0].id=order-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://order-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/orders/**

spring.cloud.gateway.server.webflux.routes[1].id=inventory-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://inventory-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/inventory/**


server.port=9090
eureka.client.service-url.defaultZone = http://localhost:8761/eureka
eureka.client.registry-fetch-interval-seconds = 5


